### ISSUE TITLE
Tracking issue for release 0.8

### ISSUE THREAD

**Issue by olivierlabayle** [olivierlabayle/TMLE.jl#62]
This is basically a full rewrite of the package, the following list may still grow:

TODO Features:

- [x] Support for covariate
- [x] Automatic Differentiation and composition
- [x] Support for probabilistic continuous Q models
- [x] Support for ordered factors treatments

TODO Documentation:
- [x] Fix Y <-> W in causal graph
- [x] Document ordered factor treatment in Dataset section

TODO General:

- [x] Outsource the interaction transformer to https://github.com/JuliaAI/MLJModels.jl/issues/476
